name: CI/CD Pipeline VZeta

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      description: Descarga el codigo del repositorio en el contenedor de GitHub Actions
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      description: Se autentica en Docker Hub usando los secretos guardados
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_PSILVA6 }}
        password: ${{ secrets.DOCKHERHUB_DCKR_PAT_BLEA_JD1YP_OQJZUN4NDIN70O1S }}

    - name: Build and Push App Image
      description: Construye la imagen de la app web y la sube a Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./myapp
        push: true
        tags: ${{ secrets.DOCKERHUB_PSILVA6 }}/myapp:latest

    - name: Build and Push Nginx Image
      description: Construye la imagen del Proxy Nginx y la sube a Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./mynginx
        push: true
        tags: ${{ secrets.DOCKERHUB_PSILVA6 }}/mynginx:latest
